objects/Applicant__c.object
<CustomObject>
    <description>To store applicant&apos;s personal details</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <label>Applicant</label>
        <referenceTo>Applicant__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <referenceTo>Job_Opening__c</referenceTo>
        <relationshipLabel>Applications (Job Id)</relationshipLabel>
        <relationshipName>Applications1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Opening__c.object
<CustomObject>
    <fields>
        <fullName>Job_Id__c</fullName>
        <displayFormat>A-{0000}</displayFormat>
        <label>Job Id</label>
        <type>AutoNumber</type>
    </fields>
    <label>Job Opening</label>
    <nameField>
        <label>Job Opening Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Openings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JobPortal.cls
@RestResource(urlMapping = '/v1/JobApplication/')
global class JobPortal {
    @httpPost
    global static  Application__c createApplications(String name, String email,String address, String phone, String jobid, String applicant){
        Applicant__c app = new Applicant__c ();
        app.name =applicant;
        app.Email__c = email;
        app.Phone__c = phone;
        app.Address__c = address;
        insert app;     
        String id =   [select id,name from Job_Opening__c where Job_Id__c =: jobid][0].id;
        String applicantName =   [select id,name from Applicant__c where Name =: applicant][0].id;
        Application__c application = new Application__c(
            Name = name,
            Email__c = email,
            Phone__c = phone,
            Job_Id__c = id,
            Applicant__c = applicantName

        );
        insert application;
        return application;
        
    }
    
}