objects/Job_Opening__c.object
<CustomObject>
    <fields>
        <fullName>Designation__c</fullName>
        <label>Designation</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <displayFormat>A-{0000}</displayFormat>
        <label>Job Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Job_Status__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Job Status</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Required_Qualification__c</fullName>
        <label>Required Qualification</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Job Opening</label>
    <nameField>
        <label>Job Opening Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Openings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/JobDetails.cls
/**
* @author      Lovish Tayal
* @date        22-Dec-2019
* @description 
* 22-Dec-2019  - Lovish Tayal - creation and inital commit                       
*/

public class JobDetails {
    @AuraEnabled
    public static List<Job_Opening__c> getJobDetails(){
       Id recId =  Schema.Sobjecttype.Job_Opening__c.getRecordTypeInfosByName().get('Internal Department').getRecordTypeId();
        List<Job_Opening__c> jobList = [select id, Name, Job_Id__c, Required_Qualification__c, Job_Status__c, Designation__c, Salary__c, RecordTypeId  from Job_Opening__c where Job_Status__c = true and RecordTypeId =: recId];
        return jobList;
    }
}